dep 'zsh.managed'

dep 'zsh', :username do
  requires 'zsh.managed'
  username.default!(shell('whoami'))

  met? { shell("sudo su - '#{username}' -c 'echo $SHELL'") == which('zsh') }
  meet { sudo("chsh -s '#{which('zsh')}' #{username}") }
end

dep 'zshrc', :username do
  requires 'zsh'.with(username)

  met? do
    shell?("diff -I '# Generated by babushka' #{source_path} #{path}")
  end

  meet do
    render_erb 'zshrc', to: path
  end

  def path
    if username == 'root'
      '/root/.zshrc'
    else
      "/Users/#{username}/.zshrc"
    end
  end

  def source_path
    @source_path ||= erb_path_for 'zshrc'
  end
end